#!/bin/bash -l

#$ -P tianlabdl

#$ -l h_rt=12:00:00

timestamp=$(date +"%Y%m%d%H%M%S%N")  # %N for nanoseconds

random_suffix=$(($RANDOM % 1000))  # Generates a random number between 0 and 999

jobname="wandb_tutorial_${timestamp}_${random_suffix}"

#$ -j y
#$ -o "/projectnb/tianlabdl/jalido/wandb_tutorial/logs/${jobname}.qlog"

#$ -l gpus=1
#$ -l gpu_c=3.5

module load python3/3.10.12
source activate .venv/bin/activate
python basic_train.py 